openapi: 3.0.0
info:
  title: Soil Health Data Management API
  description: This API provides a set of endpoints for managing soil health data.
  version: 1.0.0
paths:
  /entities:
    get:
      description: Retrieve a list of soil health entities.
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Entity'
                type: array
          description: List of soil health entities.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error.
      tags:
        - entities
    post:
      description: Creates a new soil health entity.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: Entity created successfully.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
      summary: Create a new soil health entity.
      tags:
        - entities
  /entities/{entityId}:
    delete:
      description: Delete a specific soil health entity.
      operationId: deleteEntity
      responses:
        '200':
          description: Entity deleted successfully.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Entity not found.
      tags:
        - entities
    get:
      description: Retrieve a specific soil health entity.
      operationId: getEntityById
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: Successful operation.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Entity not found.
      tags:
        - entities
    parameters:
      - description: Unique identifier for the entity.
        in: path
        name: entityId
        required: true
        schema:
          type: string
    put:
      description: Updates a specific soil health entity by its unique identifier.
      operationId: updateEntity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
        description: Entity object that needs to be updated.
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Entity not found.
      summary: Update a specific soil health entity.
      tags:
        - entities
  /entities/{entityId}/measurements:
    get:
      description: Retrieve a list of measurements for a specific soil health entity.
      operationId: getMeasurementsForEntity
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Measurement'
                type: array
          description: Successful response.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Entity not found.
      summary: Retrieve a list of measurements for a specific soil health entity.
      tags:
        - entities
    parameters:
      - description: Unique identifier for the entity.
        in: path
        name: entityId
        required: true
        schema:
          type: string
    post:
      description: Creates a new measurement for a specific soil health entity.
      operationId: createMeasurement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Measurement'
        description: Measurement object that needs to be added to the soil health entity.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Measurement'
          description: Measurement created successfully.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid input.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Entity not found.
      summary: Create a new measurement for a specific soil health entity.
      tags:
        - entities
  /measurements/{measurementId}:
    delete:
      operationId: deleteMeasurement
      responses:
        '200':
          description: Measurement deleted successfully.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Measurement not found.
      summary: Delete a specific measurement.
      tags:
        - measurements
    get:
      description: This endpoint retrieves a specific measurement by its unique identifier.
      operationId: getMeasurementById
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Measurement'
          description: Successful operation.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Measurement not found.
      summary: Retrieve a specific measurement.
      tags:
        - measurements
    parameters:
      - description: Unique identifier for the measurement.
        in: path
        name: measurementId
        required: true
        schema:
          type: string
    put:
      operationId: updateMeasurement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Measurement'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Measurement'
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Not found.
      summary: Update a specific measurement.
      tags:
        - measurements
components:
  schemas:
    Entity:
      description: Description of the soil health entity.
      properties:
        description:
          type: string
        entityId:
          type: string
        location:
          properties:
            latitude:
              type: number
            longitude:
              type: number
          type: object
        name:
          type: string
      type: object
    Error:
      description: Error object
      properties:
        message:
          description: Error message
          type: string
      type: object
    Measurement:
      description: A measurement of a soil health entity.
      properties:
        entityId:
          description: Unique identifier for the entity the measurement belongs to.
          type: string
        measurementId:
          description: Unique identifier for the measurement.
          type: string
        timestamp:
          description: Timestamp of the measurement.
          format: date-time
          type: string
        unit:
          description: Unit of the measurement.
          type: string
        value:
          description: Value of the measurement.
          type: number
      type: object
