openapi: 3.0.0
info:
  title: Crop Breeding Genetic Data API
  description: This API provides a way to manage crop breeding genetic data.
  version: 1.0.0
paths:
  /entities:
    get:
      description: List all entities
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Entity'
                type: array
          description: List of entities
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      tags:
        - entities
    post:
      description: Creates a new entity in the system.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: Entity created successfully.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error.
      summary: Create a new entity
      tags:
        - entities
  /entities/{entity}:
    delete:
      operationId: deleteEntity
      responses:
        '200':
          description: Entity deleted successfully
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Entity not found
      summary: Delete a specific entity
      tags:
        - entities
    get:
      description: Get the details of a specific entity
      operationId: getEntityById
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: Entity details
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Entity not found
      tags:
        - entities
    parameters:
      - description: Unique identifier of the entity
        in: path
        name: entity
        required: true
        schema:
          type: string
    put:
      description: Updates the details of a specific entity. The entity must already exist.
      operationId: updateEntity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
        description: The updated details of the entity.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: The updated entity.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The entity does not exist.
      summary: Update the details of a specific entity
      tags:
        - entities
  /entities/{entity}/traits:
    get:
      description: List all traits for a specific entity
      operationId: getEntityTraits
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Trait'
                type: array
          description: List of traits for the specified entity
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Entity not found
      tags:
        - entities
    parameters:
      - description: Unique identifier of the entity
        in: path
        name: entity
        required: true
        schema:
          $ref: '#/components/schemas/Entity'
    post:
      description: >-
        Creates a new trait for a specific entity. The trait is associated with
        the entity and can be used to store additional information about the
        entity.
      operationId: createTraitForEntity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trait'
        description: The trait to be created.
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trait'
          description: The trait was created successfully.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request was invalid.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The entity was not found.
      summary: Create a new trait for a specific entity
      tags:
        - entities
  /entities/{entity}/traits/{trait}:
    delete:
      description: Delete a specific trait for a specific entity
      operationId: deleteEntityTrait
      parameters:
        - description: Unique identifier of the trait
          in: path
          name: trait
          required: true
          schema:
            $ref: '#/components/schemas/Trait'
      responses:
        '200':
          description: Trait deleted successfully
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Entity or trait not found
      summary: Delete a specific trait for a specific entity
      tags:
        - entities
    get:
      description: Returns the details of a specific trait for a specific entity.
      operationId: getEntityTrait
      parameters:
        - description: The unique identifier of the trait.
          in: path
          name: trait
          required: true
          schema:
            $ref: '#/components/schemas/Trait'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trait'
          description: Successful operation.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Entity or trait not found.
      summary: Get the details of a specific trait for a specific entity
      tags:
        - entities
    parameters:
      - description: The unique identifier of the entity.
        in: path
        name: entity
        required: true
        schema:
          $ref: '#/components/schemas/Entity'
      - description: The unique identifier of the trait.
        in: path
        name: trait
        required: true
        schema:
          $ref: '#/components/schemas/Trait'
    put:
      description: >-
        Updates the details of a specific trait for a specific entity. The trait
        and entity must already exist.
      operationId: updateEntityTrait
      parameters:
        - description: The unique identifier of the trait.
          in: path
          name: trait
          required: true
          schema:
            $ref: '#/components/schemas/Trait'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trait'
        description: The updated details of the trait.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trait'
          description: The updated trait details.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified entity or trait does not exist.
      summary: Update the details of a specific trait for a specific entity
      tags:
        - entities
components:
  schemas:
    Entity:
      description: Description of the entity
      properties:
        description:
          type: string
        id:
          type: string
        name:
          type: string
      type: object
    Error:
      description: Error object
      properties:
        message:
          description: Error message
          type: string
      type: object
    Trait:
      description: A trait of an entity.
      properties:
        description:
          description: Description of the trait.
          type: string
        id:
          description: Unique identifier of the trait.
          type: string
        name:
          description: Name of the trait.
          type: string
        value:
          description: Value of the trait.
          type: string
      type: object
